---
# yamllint disable rule:line-length
# yamllint disable rule:truthy

- block:
    - include: facts.yml
    - include: packages.yml
    - include: configure.yml
    - include: test.yml
  tags:
    - logwatch

...
