---
# yamllint disable rule:line-length
# yamllint disable rule:truthy

galaxy_info:
  author: Pavel Kim
  description: Installs and configures logrotate
  license: GPLv3
  
  min_ansible_version: 1.2

  galaxy_tags:
    - rhel
    - centos
    - linux
    - logging
    - logwatch

dependencies: []

...
